import Head from "next/head";
import Image from "next/image";
import Container from "../components/Container";
import styles from "../styles/Home.module.css";

const Design = () => {
  return (
    <div style={{ width: "100vw" }} className=' m-0'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Container />
    </div>
  );
};

export default Design;
